import React from 'react';
import Link from 'next/link';

const teal = '#00d4aa';
const muted = '#7a9ab0';
const dim = '#4a6272';
const bright = '#dce8f0';
const border = '#00422e';

export default function PrivacyPage() {
  return (
    <main style={{ backgroundColor: '#080e12', color: '#dce8f0', minHeight: '100vh' }}>
      <div style={{ maxWidth: '768px', margin: '0 auto', padding: '64px 24px' }}>

        {/* Back link */}
        <Link href="/" style={{ color: teal, fontSize: '14px', textDecoration: 'none', display: 'inline-block', marginBottom: '40px' }}>
          ← Back to leados.tech
        </Link>

        {/* Header */}
        <div style={{ marginBottom: '48px' }}>
          <h1 style={{ color: bright, fontSize: '2.25rem', fontWeight: 300, marginBottom: '12px' }}>
            Privacy Policy
          </h1>
          <p style={{ color: muted, fontSize: '14px' }}>
            Effective date: April 10, 2026 &nbsp;|&nbsp; Last updated: April 10, 2026
          </p>
        </div>

        {/* Sections */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '48px', fontSize: '14px', lineHeight: '1.7' }}>

          {/* 1 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>1 — Who We Are</h2>
            <p style={{ color: muted, marginBottom: '12px' }}>
              LeadOS is operated by <strong style={{ color: bright }}>Kristine Bjørgan Østby</strong>, a sole trader (enkeltpersonforetak) based in Norway. We are the data controller for personal data processed through this service.
            </p>
            <p style={{ color: muted }}>
              Contact: <a href="mailto:hello@leados.tech" style={{ color: teal }}>hello@leados.tech</a>
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>2 — Legal Basis for Processing (GDPR Article 6)</h2>
            <p style={{ color: muted, marginBottom: '16px' }}>We process your personal data on the following legal bases:</p>
            <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '10px' }}>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Contract performance (Art. 6(1)(b))</strong> — processing your account data, ICP configuration, and leads is necessary to provide the service you signed up for.</span></li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Legitimate interest (Art. 6(1)(f))</strong> — usage analytics to improve the service.</span></li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Legal obligation (Art. 6(1)(c))</strong> — retaining transaction records for tax and accounting purposes.</span></li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Consent (Art. 6(1)(a))</strong> — cookies that are not strictly necessary.</span></li>
            </ul>
          </section>

          {/* 3 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>3 — What Personal Data We Collect</h2>
            <p style={{ color: bright, fontWeight: 500, marginBottom: '8px' }}>Data you provide directly:</p>
            <ul style={{ listStyle: 'none', padding: 0, margin: '0 0 20px 0', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>Name and email address (account registration)</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>Company URL and business description (onboarding)</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>ICP configuration (target customer profile, signals, disqualifiers)</li>
            </ul>
            <p style={{ color: bright, fontWeight: 500, marginBottom: '8px' }}>Data generated by the service:</p>
            <ul style={{ listStyle: 'none', padding: 0, margin: '0 0 20px 0', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>Lead records including company names, contact names, email addresses, phone numbers, and LinkedIn URLs sourced from third-party databases</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>Outreach drafts you create</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>Reply notes and pipeline status you set</li>
            </ul>
            <p style={{ color: bright, fontWeight: 500, marginBottom: '8px' }}>Technical data collected automatically:</p>
            <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>IP address and browser/device information</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>Pages visited and features used (analytics)</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>Cookie identifiers (see Section 9)</li>
            </ul>
          </section>

          {/* 4 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>4 — How We Use Your Data</h2>
            <ul style={{ listStyle: 'none', padding: 0, margin: '0 0 20px 0', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>To create and manage your account</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>To run the AI lead generation agent on your behalf</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>To store and display your leads, pipeline, and outreach history</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>To process payments and manage your subscription</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>To send transactional emails (account confirmation, receipts)</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>To improve and debug the service</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>To comply with legal obligations</li>
            </ul>
            <p style={{ color: muted }}>
              We do not sell your data. We do not use your data for advertising. We do not share your data with third parties except as described in Section 5.
            </p>
          </section>

          {/* 5 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>5 — Third-Party Data Processors</h2>
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
                <thead>
                  <tr style={{ borderBottom: `1px solid ${border}` }}>
                    <th style={{ color: bright, textAlign: 'left', padding: '8px 16px 8px 0', fontWeight: 500 }}>Processor</th>
                    <th style={{ color: bright, textAlign: 'left', padding: '8px 16px 8px 0', fontWeight: 500 }}>Purpose</th>
                    <th style={{ color: bright, textAlign: 'left', padding: '8px 16px 8px 0', fontWeight: 500 }}>Location</th>
                    <th style={{ color: bright, textAlign: 'left', padding: '8px 0 8px 0', fontWeight: 500 }}>Safeguard</th>
                  </tr>
                </thead>
                <tbody>
                  <tr style={{ borderBottom: `1px solid ${border}` }}>
                    <td style={{ color: bright, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Supabase</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Database and authentication</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>EU (West EU region)</td>
                    <td style={{ color: muted, padding: '12px 0', verticalAlign: 'top' }}>GDPR compliant, DPA in place</td>
                  </tr>
                  <tr style={{ borderBottom: `1px solid ${border}` }}>
                    <td style={{ color: bright, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Anthropic</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>AI processing of website content and lead scoring</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>USA</td>
                    <td style={{ color: muted, padding: '12px 0', verticalAlign: 'top' }}>Standard Contractual Clauses (SCCs)</td>
                  </tr>
                  <tr style={{ borderBottom: `1px solid ${border}` }}>
                    <td style={{ color: bright, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Vercel</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Application hosting and edge delivery</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>USA/EU</td>
                    <td style={{ color: muted, padding: '12px 0', verticalAlign: 'top' }}>Standard Contractual Clauses (SCCs)</td>
                  </tr>
                  <tr style={{ borderBottom: `1px solid ${border}` }}>
                    <td style={{ color: bright, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Lemonsqueezy</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Payment processing and subscription management</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>USA</td>
                    <td style={{ color: muted, padding: '12px 0', verticalAlign: 'top' }}>Standard Contractual Clauses (SCCs)</td>
                  </tr>
                  <tr style={{ borderBottom: `1px solid ${border}` }}>
                    <td style={{ color: bright, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Serper.dev</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Google search API for lead discovery</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>USA</td>
                    <td style={{ color: muted, padding: '12px 0', verticalAlign: 'top' }}>Standard Contractual Clauses (SCCs)</td>
                  </tr>
                  <tr style={{ borderBottom: `1px solid ${border}` }}>
                    <td style={{ color: bright, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Apollo.io</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Contact enrichment (email, phone, LinkedIn)</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>USA</td>
                    <td style={{ color: muted, padding: '12px 0', verticalAlign: 'top' }}>Standard Contractual Clauses (SCCs)</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>

          {/* 6 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>6 — International Data Transfers</h2>
            <p style={{ color: muted }}>
              Some of our processors are based in the United States. When we transfer personal data outside the European Economic Area (EEA), we ensure appropriate safeguards are in place in accordance with GDPR Chapter V, specifically Standard Contractual Clauses (SCCs) as approved by the European Commission.
            </p>
          </section>

          {/* 7 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>7 — Automated Decision-Making</h2>
            <p style={{ color: muted }}>
              LeadOS uses AI (Claude by Anthropic) to automatically score leads based on your ICP configuration. This constitutes automated processing under GDPR Article 22. However, this scoring is not a legally or similarly significant decision — it is an advisory ranking to help you prioritise outreach. You retain full control and can override or ignore any score. No leads are contacted without your explicit approval.
            </p>
          </section>

          {/* 8 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>8 — Data Retention</h2>
            <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '10px' }}>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Account data</strong> — retained for the duration of your subscription and deleted within 30 days of account deletion.</span></li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Lead data</strong> — retained for the duration of your subscription and deleted within 30 days of account deletion.</span></li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Payment records</strong> — retained for 5 years to comply with Norwegian accounting law (Bokf&oslash;ringsloven).</span></li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Backup data</strong> — may persist in encrypted backups for up to 90 days after deletion.</span></li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Analytics data</strong> — retained in aggregate, anonymised form indefinitely.</span></li>
            </ul>
          </section>

          {/* 9 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>9 — Cookies</h2>
            <div style={{ overflowX: 'auto', marginBottom: '16px' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
                <thead>
                  <tr style={{ borderBottom: `1px solid ${border}` }}>
                    <th style={{ color: bright, textAlign: 'left', padding: '8px 16px 8px 0', fontWeight: 500 }}>Cookie</th>
                    <th style={{ color: bright, textAlign: 'left', padding: '8px 16px 8px 0', fontWeight: 500 }}>Purpose</th>
                    <th style={{ color: bright, textAlign: 'left', padding: '8px 16px 8px 0', fontWeight: 500 }}>Type</th>
                    <th style={{ color: bright, textAlign: 'left', padding: '8px 0', fontWeight: 500 }}>Duration</th>
                  </tr>
                </thead>
                <tbody>
                  <tr style={{ borderBottom: `1px solid ${border}` }}>
                    <td style={{ color: bright, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Supabase auth token</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Keeps you logged in</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Strictly necessary</td>
                    <td style={{ color: muted, padding: '12px 0', verticalAlign: 'top' }}>Session</td>
                  </tr>
                  <tr style={{ borderBottom: `1px solid ${border}` }}>
                    <td style={{ color: bright, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Consent cookie</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Remembers your cookie preferences</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Strictly necessary</td>
                    <td style={{ color: muted, padding: '12px 0', verticalAlign: 'top' }}>1 year</td>
                  </tr>
                  <tr style={{ borderBottom: `1px solid ${border}` }}>
                    <td style={{ color: bright, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Hotjar</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>User behaviour analytics</td>
                    <td style={{ color: muted, padding: '12px 16px 12px 0', verticalAlign: 'top' }}>Analytics (requires consent)</td>
                    <td style={{ color: muted, padding: '12px 0', verticalAlign: 'top' }}>1 year</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p style={{ color: muted }}>
              You can withdraw consent for non-essential cookies at any time by clicking &quot;Cookie settings&quot; in the footer.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>10 — Your Rights Under GDPR</h2>
            <ul style={{ listStyle: 'none', padding: 0, margin: '0 0 20px 0', display: 'flex', flexDirection: 'column', gap: '10px' }}>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Right of access (Art. 15)</strong> — request a copy of all data we hold about you.</span></li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Right to rectification (Art. 16)</strong> — request correction of inaccurate data.</span></li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Right to erasure (Art. 17)</strong> — request deletion of your data (&ldquo;right to be forgotten&rdquo;).</span></li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Right to restriction of processing (Art. 18)</strong> — request we limit how we use your data.</span></li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Right to data portability (Art. 20)</strong> — receive your data in a machine-readable format.</span></li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Right to object (Art. 21)</strong> — object to processing based on legitimate interest.</span></li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span><span><strong style={{ color: bright }}>Right to withdraw consent</strong> — where processing is based on consent, you can withdraw at any time.</span></li>
            </ul>
            <p style={{ color: muted }}>
              To exercise any of these rights, email <a href="mailto:hello@leados.tech" style={{ color: teal }}>hello@leados.tech</a>. We will respond within 30 days.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>11 — Data Security</h2>
            <p style={{ color: muted, marginBottom: '16px' }}>We implement appropriate technical and organisational measures to protect your data including:</p>
            <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>Encrypted data storage (Supabase with encryption at rest)</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>HTTPS/TLS encryption in transit</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>Row-level security on all database tables</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>API keys stored as environment variables, never in code</li>
              <li style={{ color: muted, display: 'flex', gap: '8px' }}><span style={{ color: teal }}>·</span>Access limited to the data controller only</li>
            </ul>
          </section>

          {/* 12 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>12 — Children&apos;s Privacy</h2>
            <p style={{ color: muted }}>
              LeadOS is a B2B service intended for business use only. We do not knowingly collect data from anyone under the age of 18.
            </p>
          </section>

          {/* 13 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>13 — Changes to This Policy</h2>
            <p style={{ color: muted }}>
              We may update this Privacy Policy from time to time. We will notify you by email at least 14 days before any material changes take effect. Continued use of the service after that date constitutes acceptance of the updated policy.
            </p>
          </section>

          {/* 14 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>14 — Complaints</h2>
            <p style={{ color: muted, marginBottom: '16px' }}>
              If you believe we are processing your data unlawfully, you have the right to lodge a complaint with the Norwegian data protection authority:
            </p>
            <div style={{ border: `1px solid ${border}`, borderRadius: '8px', padding: '16px 20px' }}>
              <p style={{ color: bright, fontWeight: 500, marginBottom: '8px' }}>Datatilsynet</p>
              <a href="https://www.datatilsynet.no" target="_blank" rel="noopener noreferrer" style={{ color: teal, display: 'block', marginBottom: '4px' }}>datatilsynet.no</a>
              <p style={{ color: muted, marginBottom: '4px' }}>+47 22 39 69 00</p>
              <p style={{ color: muted }}>Postboks 458 Sentrum, 0105 Oslo</p>
            </div>
          </section>

          {/* 15 */}
          <section>
            <h2 style={{ color: teal, fontSize: '15px', fontWeight: 500, marginBottom: '16px' }}>15 — Contact</h2>
            <p style={{ color: muted }}>
              For any privacy-related questions or to exercise your rights: <a href="mailto:hello@leados.tech" style={{ color: teal }}>hello@leados.tech</a>
            </p>
          </section>

        </div>

        {/* Footer nav */}
        <div style={{ borderTop: '1px solid #0e1822', marginTop: '64px', paddingTop: '32px', display: 'flex', gap: '24px' }}>
          <Link href="/terms" style={{ color: dim, fontSize: '12px', textDecoration: 'none' }}>Terms of Service</Link>
          <Link href="/" style={{ color: dim, fontSize: '12px', textDecoration: 'none' }}>Back to LeadOS</Link>
        </div>

      </div>
    </main>
  );
}
